spring.application.name=KCPortfolio
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_kc
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your@gmail.com
spring.mail.password=your_app_password

jwt.secret=your_secret_key
jwt.expiration=86400000


portfolio.owner.email=choprakunal329@gmail.com
portfolio.owner.name=Kunal_Chopra